debug: false

server:
  port: 8084
  shutdown: graceful

spring:
  profiles:
    active: dev
  application:
    name: data-ai
  main:
    web-application-type: SERVLET
  data:
    mongodb:
      uri: ${MONGO_URL}
      auto-index-creation: true
  threads:
    virtual:
      enabled: true
  ai:
    openai.api-key: ${spring.ai.openai.api-key}
    ollama:
      base-url: ${spring.ai.ollama.base-url}
      chat:
        options:
          model: ${spring.ai.ollama.chat.model}
          temperature: 0.7
        enabled: true