debug: false

server:
  port: 8084
  shutdown: graceful

spring:
  profiles:
    active: dev
  application:
    name: data-ai
  main:
    web-application-type: SERVLET
  data:
    mongodb:
      uri: ${MONGO_URL}
      auto-index-creation: true
  threads:
    virtual:
      enabled: true
  ai:
    openai.api-key: ${OPEN_API_KEY}
    ollama:
      base-url: ${OLLAMA_URL}
      chat:
        options:
          model: ${OLLAMA_MODEL}
          temperature: 0.7
        enabled: true