apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: mercury-microservice
  labels:
    name: consumer-service
    app: consumer-app
spec:
  type: NodePort
  ports:
    - port: 8081
      protocol: TCP
  selector:
    app: consumer-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: mercury-microservice
  labels:
    name: consumer-deployment
    app: consumer-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      name: consumer-deployed-pod
      namespace: mercury-microservice
      labels:
        app: consumer-app
    spec:
      containers:
        - name: consumer
          image: 10austin/data-consumer
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password1234
            - name: MONGO_DB_NAME
              value: mercury
            - name: MONGO_URL
              value: mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@$(MONGO_SERVICE_SERVICE_HOST):$(MONGO_SERVICE_SERVICE_PORT)/$(MONGO_DB_NAME)?authSource=admin #mongodb://host:27017/db
            - name: KAFKA_URL
              value: kafka-headless:9092
