apiVersion: v1
kind: Service
metadata:
  name: via-kafka-service
  namespace: mercury-microservice
  labels:
    name: via-kafka-service
    app: via-kafka-app
spec:
  type: NodePort
  ports:
    - port: 8082
      protocol: TCP
  selector:
    app: via-kafka-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: via-kafka-deployment
  namespace: mercury-microservice
  labels:
    name: via-kafka-deployment
    app: via-kafka-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: via-kafka-app
  template:
    metadata:
      name: via-kafka-deployed-pod
      namespace: mercury-microservice
      labels:
        app: via-kafka-app
    spec:
      containers:
        - name: via-kafka
          image: 10austin/data-via-kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              protocol: TCP
          env:
            - name: KAFKA_URL
              value: 0.0.0.0:9092
