apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: mercury-microservice
  labels:
    name: ai-service
    app: ai-app
spec:
  type: NodePort
  ports:
    - port: 8084
      protocol: TCP
  selector:
    app: ai-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deployment
  namespace: mercury-microservice
  labels:
    name: ai-deployment
    app: ai-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-app
  template:
    metadata:
      name: ai-deployed-pod
      namespace: mercury-microservice
      labels:
        app: ai-app
    spec:
      containers:
        - name: consumer
          image: 10austin/data-ai
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password1234
            - name: MONGO_DB_NAME
              value: mercury
            - name: MONGO_URL
              value: mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@$(MONGO_SERVICE_SERVICE_HOST):$(MONGO_SERVICE_SERVICE_PORT)/$(MONGO_DB_NAME)?authSource=admin #mongodb://host:27017/db
            - name: OLLAMA_URL
              value: http://ollama-headless:11434

