apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-mercury
  namespace: mercury-microservice
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: "/tmp/mysql-data-pv-mercury"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-mercury
  namespace: mercury-microservice
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mercury-microservice
  labels:
    tier: mysql-database-tier
spec:
  type: NodePort
  ports:
    - port: 3306
  selector:
    app: mysql-database-tier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mercury-microservice
  labels:
    name: mercury-app
    tier: mysql-database-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: mysql-database-tier
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: mercury-microservice
      name: mysql
      labels:
        tier: mysql-database-tier
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /data/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc-mercury
      restartPolicy: Always