server:
  port: 8082
  shutdown: graceful

springdoc:
  api-docs:
    path: /v3/swagger-ui.html
  swagger-ui:
    path: /v3/api-docs

spring:
  profiles:
    active: dev
  main:
    web-application-type: REACTIVE
  threads:
    virtual:
      enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration, org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  kafka:
    bootstrap-servers:
      - ${KAFKA_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
    streams:
      replication-factor: 3

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
  info:
    build:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,beans
  prometheus:
    metrics:
      export:
        enabled: true
        descriptions: true