server:
  port: 8081
  shutdown: graceful

springdoc:
  api-docs:
    path: /v3/swagger-ui.html
  swagger-ui:
    path: /v3/api-docs

spring:
  profiles:
    active: dev
  main:
    web-application-type: REACTIVE
  data:
    mongodb:
      uri: ${MONGO_URL}
      auto-index-creation: true
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers:
      - ${KAFKA_URL}
    consumer:
      group-id: stream-transaction-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "group.instance.id": "1"
        "spring.json.value.default.type": "com.github.hth.dataconsumer.dto.CreditTransactionDTO"
        "spring.json.type.mapping": "com.github.hth.dataviakafka.dto.CreditTransactionDTO:com.github.hth.dataconsumer.dto.CreditTransactionDTO"
        "spring.json.trusted.packages": "com.github.hth.dataviakafka.dto.CreditTransactionDTO"

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
  info:
    build:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,beans
  prometheus:
    metrics:
      export:
        enabled: true
        descriptions: true