server:
  port: 8081
  shutdown: graceful

springdoc:
  api-docs:
    path: /v3/swagger-ui.html
  swagger-ui:
    path: /v3/api-docs

spring:
  main:
    web-application-type: REACTIVE
  data:
    mongodb:
      uri: ${MONGO_URL}
      auto-index-creation: true
  threads:
    virtual:
      enabled: true

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
  info:
    build:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,beans
  prometheus:
    metrics:
      export:
        enabled: true
        descriptions: true